//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class BatsmanInning
    {
        public BatsmanInning()
        {
            this.Deliveries = new HashSet<Delivery>();
        }
    
        public int Id { get; set; }
        public System.Guid SessionId { get; set; }
        public int Runs { get; set; }
        public int Balls { get; set; }
        public double StrikeRate { get; set; }
        public int DotBalls { get; set; }
        public int Fours { get; set; }
        public int Sixes { get; set; }
        public int Singles { get; set; }
        public int Doubles { get; set; }
        public int Threes { get; set; }
    
        public virtual ICollection<Delivery> Deliveries { get; set; }
    }
}
