//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Delivery
    {
        public int Id { get; set; }
        public int InningsId { get; set; }
        public int OverId { get; set; }
        public int Runs { get; set; }
        public Nullable<Extra> Extra { get; set; }
        public Nullable<int> ShotX { get; set; }
        public Nullable<int> ShotY { get; set; }
        public Nullable<DismissalType> DismissalType { get; set; }
        public Nullable<System.Guid> FielderId { get; set; }
        public Nullable<System.Guid> ThrowCollectorId { get; set; }
        public int Order { get; set; }
        public RunType RunType { get; set; }
    
        public virtual BatsmanInning BatsmanInning { get; set; }
        public virtual Over Over { get; set; }
    }
}
