//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    
    public enum DismissalType : int
    {
        Bold = 0,
        Caught = 1,
        CaughtAndBold = 2,
        Runout = 3,
        Stumped = 4,
        HitWicket = 5
    }
}
