//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class NetSession
    {
        public NetSession()
        {
            this.Players = new HashSet<Player>();
        }
    
        public int Id { get; set; }
        public System.Guid RosterId { get; set; }
        public int OversPerBatsman { get; set; }
        public System.DateTime StartTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public bool CountingRuns { get; set; }
        public bool CountingDismissals { get; set; }
        public bool RunsBehindWicket { get; set; }
    
        public virtual Roster Roster { get; set; }
        public virtual ICollection<Player> Players { get; set; }
    }
}
