//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Over
    {
        public Over()
        {
            this.Deliveries = new HashSet<Delivery>();
            this.Spells = new HashSet<Spell>();
        }
    
        public int Id { get; set; }
        public int SpellId { get; set; }
        public int Runs { get; set; }
        public int Wickets { get; set; }
        public int Wides { get; set; }
        public int Byes { get; set; }
        public int OverStepNoBall { get; set; }
        public int HeightNoBall { get; set; }
        public int LegByes { get; set; }
        public int Order { get; set; }
    
        public virtual ICollection<Delivery> Deliveries { get; set; }
        public virtual ICollection<Spell> Spells { get; set; }
    }
}
