//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Player
    {
        public Player()
        {
            this.RosterMemberships = new HashSet<RosterMembership>();
            this.NetSessions = new HashSet<NetSession>();
        }
    
        public System.Guid Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string MiddleName { get; set; }
        public Nullable<int> Age { get; set; }
        public bool WicketKeeper { get; set; }
        public bool Batsman { get; set; }
        public bool Bowler { get; set; }
        public string Email { get; set; }
        public string PictureUri { get; set; }
    
        public virtual ICollection<RosterMembership> RosterMemberships { get; set; }
        public virtual ICollection<NetSession> NetSessions { get; set; }
    }
}
