//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Roster
    {
        public Roster()
        {
            this.NetSessions = new HashSet<NetSession>();
            this.RosterMemberships = new HashSet<RosterMembership>();
        }
    
        public System.Guid Id { get; set; }
        public string Name { get; set; }
        public string PictureUri { get; set; }
    
        public virtual ICollection<NetSession> NetSessions { get; set; }
        public virtual ICollection<RosterMembership> RosterMemberships { get; set; }
    }
}
